backend:
  name: github
  repo: yugvionai/yugvion-ai-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }